/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\avatar.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/avatar.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips_1} />
          <skinnedMesh name="Streamoji_Body" geometry={nodes.Streamoji_Body.geometry} material={materials.Streamoji_Body} skeleton={nodes.Streamoji_Body.skeleton} />
          <skinnedMesh name="Streamoji_Outfit_Bottom" geometry={nodes.Streamoji_Outfit_Bottom.geometry} material={materials.Streamoji_Outfit_Bottom} skeleton={nodes.Streamoji_Outfit_Bottom.skeleton} />
          <skinnedMesh name="Streamoji_Outfit_Footwear" geometry={nodes.Streamoji_Outfit_Footwear.geometry} material={materials.Streamoji_Outfit_Footwear} skeleton={nodes.Streamoji_Outfit_Footwear.skeleton} />
          <skinnedMesh name="Streamoji_Outfit_Top" geometry={nodes.Streamoji_Outfit_Top.geometry} material={materials.Streamoji_Outfit_Top} skeleton={nodes.Streamoji_Outfit_Top.skeleton} />
        </group>
        <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Streamoji_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
        <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Streamoji_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
        <skinnedMesh name="Streamoji_Head" geometry={nodes.Streamoji_Head.geometry} material={materials.Streamoji_Skin} skeleton={nodes.Streamoji_Head.skeleton} morphTargetDictionary={nodes.Streamoji_Head.morphTargetDictionary} morphTargetInfluences={nodes.Streamoji_Head.morphTargetInfluences} />
        <skinnedMesh name="Streamoji_Teeth" geometry={nodes.Streamoji_Teeth.geometry} material={materials.Streamoji_Teeth} skeleton={nodes.Streamoji_Teeth.skeleton} morphTargetDictionary={nodes.Streamoji_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Streamoji_Teeth.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload('/avatar.glb')
