/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\avatar.glb -o .\src\components\Avatar.jsx -k -r public 
*/

import React, { useEffect, useRef } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations, useFBX, useScroll } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";
import { useMobile } from "../hooks/useMobile";
export function Avatar(props) {
  const { isMobile } = useMobile();
  const group = React.useRef();
  const { scene } = useGLTF("/models/avatar.glb");
  const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
  const { animations: walkingAnimation } = useFBX("/animations/Walking.fbx");
  idleAnimation[0].name = "Idle";
  walkingAnimation[0].name = "Walking";

  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(
    [idleAnimation[0], walkingAnimation[0]],
    group,
  );
  const [animation, setAnimation] = React.useState("Walking");
  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation]);

  const scrollData = useScroll();
  const lastScroll = useRef(0);

  useFrame(() => {
    const scrollDelta = scrollData.offset - lastScroll.current;
    let rotationTarget = 0;
    if (Math.abs(scrollDelta) > 0.00001) {
      setAnimation("Walking");
      if (scrollDelta > 0) {
        rotationTarget = isMobile ? Math.PI/2 :0;
      } else {
        rotationTarget = isMobile ? -Math.PI/2 : Math.PI;
      }
    } else {
      setAnimation("Idle");
    }
    group.current.rotation.y = THREE.MathUtils.lerp(
      group.current.rotation.y,
      rotationTarget,
      0.1,
    );
    lastScroll.current = scrollData.offset;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Streamoji_Body"
            geometry={nodes.Streamoji_Body.geometry}
            material={materials.Streamoji_Body}
            skeleton={nodes.Streamoji_Body.skeleton}
          />
          <skinnedMesh
            name="Streamoji_Outfit_Bottom"
            geometry={nodes.Streamoji_Outfit_Bottom.geometry}
            material={materials.Streamoji_Outfit_Bottom}
            skeleton={nodes.Streamoji_Outfit_Bottom.skeleton}
          />
          <skinnedMesh
            name="Streamoji_Outfit_Footwear"
            geometry={nodes.Streamoji_Outfit_Footwear.geometry}
            material={materials.Streamoji_Outfit_Footwear}
            skeleton={nodes.Streamoji_Outfit_Footwear.skeleton}
          />
          <skinnedMesh
            name="Streamoji_Outfit_Top"
            geometry={nodes.Streamoji_Outfit_Top.geometry}
            material={materials.Streamoji_Outfit_Top}
            skeleton={nodes.Streamoji_Outfit_Top.skeleton}
          />
        </group>
        <skinnedMesh
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Streamoji_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        />
        <skinnedMesh
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Streamoji_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        />
        <skinnedMesh
          name="Streamoji_Head"
          geometry={nodes.Streamoji_Head.geometry}
          material={materials.Streamoji_Skin}
          skeleton={nodes.Streamoji_Head.skeleton}
          morphTargetDictionary={nodes.Streamoji_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Streamoji_Head.morphTargetInfluences}
        />
        <skinnedMesh
          name="Streamoji_Teeth"
          geometry={nodes.Streamoji_Teeth.geometry}
          material={materials.Streamoji_Teeth}
          skeleton={nodes.Streamoji_Teeth.skeleton}
          morphTargetDictionary={nodes.Streamoji_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Streamoji_Teeth.morphTargetInfluences}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/avatar.glb");
useFBX.preload("/animations/Idle.fbx");
useFBX.preload("/animations/Walking.fbx");
